spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/backend
        username: backend
        password: admin
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
